// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5124.JohnsonReboot.subsystems;

import org.usfirst.frc5124.JohnsonReboot.RobotMap;
import org.usfirst.frc5124.JohnsonReboot.commands.*;
import edu.wpi.first.wpilibj.Solenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Loader extends Subsystem {

    
    private final Solenoid loaderSolenoid = RobotMap.loaderLoaderSolenoid;

    
    public void initDefaultCommand() {
        
    }
    
    public void out() {
    	loaderSolenoid.set(true);
    }
    
    public void in() {
    	loaderSolenoid.set(false);
    }
}

